import type { Metadata } from "next";
import "@/styles/globals.css";
import { ConsentProvider } from "@/components/consent/ConsentProvider";
import CookieBanner from "@/components/consent/CookieBanner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <ConsentProvider>
        <CookieBanner />
        <body className={`$ antialiased mt-14 bg-[#050B1A] `}>{children}</body>
      </ConsentProvider>
    </html>
  );
}
