import type { Metadata } from "next";
import "@/styles/globals.css";
import { Navbar } from "@/components/base/nav/Navbar";
import Footer from "@/components/base/footer/Footer";
import Header from "@/components/base/header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar />
      {children}
      <Footer />
    </>
  );
}
